{{- if .Values.ordercreationqueries.autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "servicesou.ordercreationqueries.fullname" . }}
  labels:
    {{- include "servicesou.ordercreationqueries.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "servicesou.ordercreationqueries.fullname" . }}
  minReplicaCount: {{ .Values.ordercreationqueries.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.ordercreationqueries.autoscaling.maxReplicas }}
  triggers:
  {{- if .Values.ordercreationqueries.autoscaling.threshold }}
  - type: prometheus
    metadata:
      serverAddress: {{ .Values.ordercreationqueries.autoscaling.prometheusUrl }}
      metricName: {{ .Values.ordercreationqueries.autoscaling.metricName }}
      query: sum(rate({{ .Values.ordercreationqueries.autoscaling.metricName }}{service="{{ .Values.ordercreationqueries.fullnameOverride }}"}[2m]))
      threshold: "{{ .Values.ordercreationqueries.autoscaling.threshold }}"
  {{- end }}
{{- end }}
