{{- if .Values.changestatusbc.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "changestatus.changestatusbc.serviceAccountName" . }}
  labels:
    {{- include "changestatus.changestatusbc.labels" . | nindent 4 }}
  {{- with .Values.changestatusbc.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
