{{- if .Values.changestatusor.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "changestatus.changestatusor.serviceAccountName" . }}
  labels:
    {{- include "changestatus.changestatusor.labels" . | nindent 4 }}
  {{- with .Values.changestatusor.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
