{{- if .Values.ordercreationqueries.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "servicesou.ordercreationqueries.serviceAccountName" . }}
  labels:
    {{- include "servicesou.ordercreationqueries.labels" . | nindent 4 }}
  {{- with .Values.ordercreationqueries.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
