version: "3.8"
services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
  posv2:
    container_name: posv2
    build:
      context: posv2
      dockerfile: Dockerfile
    environment:
      - POSV2_MYSQL_HOST=${DOCKER_GATEWAY_HOST:-host.docker.internal}
    network:
      - posv2-network
    ports:
      - '8095:8080'
    restart: always
    volumes:
      - ./posv2:/posv2
    working_dir: /posv2
volumes:
  dbdata:
    driver: local
networks:
  posv2-network:
    driver: bridge