{{- if .Values.orderorlocalserver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "servicesou.orderorlocalserver.serviceAccountName" . }}
  labels:
    {{- include "servicesou.orderorlocalserver.labels" . | nindent 4 }}
  {{- with .Values.orderorlocalserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
