{{- if .Values.ordercreation.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "servicesou.ordercreation.serviceAccountName" . }}
  labels:
    {{- include "servicesou.ordercreation.labels" . | nindent 4 }}
  {{- with .Values.ordercreation.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
