apiVersion: v1
kind: Service
metadata:
  name: {{ include "servicesou.ordercreation.fullname" . }}
  labels:
    {{- include "servicesou.ordercreation.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ordercreation.service.type }}
  ports:
    - port: {{ .Values.ordercreation.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "servicesou.ordercreation.selectorLabels" . | nindent 4 }}
