package com.robinfood.core.constants;

public class CommandHandlerConstants {

    //Single
    public static final String EXECUTE_COMMAND_SAVE_INPUT_REQUEST = "COMMAND_SAVE_INPUT_REQUEST";
    public static final String EXECUTE_COMMAND_INPUT_REQUEST_VALIDATION = "EXECUTE_COMMAND_INPUT_REQUEST_VALIDATION";
    public static final String EXECUTE_COMMAND_ROUND_VALUES_TRANSACTION = "EXECUTE_COMMAND_ROUND_VALUES_TRANSACTION";
    public static final String EXECUTE_COMMAND_CONVERT_IDS_TRANSACTION_TO_NULL = "EXECUTE_COMMAND_CONVERT_IDS_TRANSACTION_TO_NULL";
    public static final String EXECUTE_COMMAND_VALIDATE_PAYMENT_METHOD_PAID = "EXECUTE_COMMAND_VALIDATE_PAYMENT_METHOD_PAID";
    public static final String EXECUTE_COMMAND_SEND_ORDER_DISCARDED_TO_QUEUE = "EXECUTE_COMMAND_SEND_ORDER_DISCARDED_TO_QUEUE";
    public static final String EXECUTE_COMMAND_SAVE_TEMPORARY_TRANSACTION_VALIDATING_PAYMENT_METHODS = "EXECUTE_COMMAND_SAVE_TEMPORARY_TRANSACTION_VALIDATING_PAYMENT_METHODS";
    public static final String EXECUTE_COMMAND_GET_TRANSACTION_UUID = "EXECUTE_COMMAND_GET_TRANSACTION_UUID";
    public static final String EXECUTE_COMMAND_INFORMATION_BY_STORE = "EXECUTE_COMMAND_INFORMATION_BY_STORE";
    public static final String EXECUTE_COMMAND_GET_CHANNEL = "EXECUTE_COMMAND_GET_CHANNEL";
    public static final String EXECUTE_COMMAND_VALIDATE_SERVICE = "EXECUTE_COMMAND_VALIDATE_SERVICE";
    public static final String EXECUTE_COMMAND_VALIDATE_CO2 = "EXECUTE_COMMAND_VALIDATE_CO2";
    public static final String EXECUTE_COMMAND_VALIDATE_MENU = "EXECUTE_COMMAND_VALIDATE_MENU";
    public static final String EXECUTE_COMMAND_GET_MENU_HALL_PRODUCT_DETAIL = "EXECUTE_COMMAND_GET_MENU_HALL_PRODUCT_DETAIL";
    public static final String EXECUTE_COMMAND_VALIDATE_DISCOUNTS = "EXECUTE_COMMAND_VALIDATE_DISCOUNTS";
    public static final String EXECUTE_COMMAND_VALIDATE_COUPONS = "EXECUTE_COMMAND_VALIDATE_COUPONS";
    public static final String EXECUTE_COMMAND_VALIDATE_FOOD_COINS = "EXECUTE_COMMAND_VALIDATE_FOOD_COINS";
    public static final String EXECUTE_COMMAND_GET_FINAL_PRODUCT_TAXES = "EXECUTE_COMMAND_GET_FINAL_PRODUCT_TAXES";
    public static final String EXECUTE_COMMAND_GET_FINAL_PRODUCT_FINANCE_CATEGORIES = "EXECUTE_COMMAND_GET_FINAL_PRODUCT_FINANCE_CATEGORIES";
    public static final String EXECUTE_COMMAND_POS_INFORMATION = "EXECUTE_COMMAND_POS_INFORMATION";
    public static final String EXECUTE_COMMAND_CREATION_TRANSACTION = "EXECUTE_COMMAND_CREATION_TRANSACTION";
    public static final String EXECUTE_COMMAND_SAVE_REQUEST_ORDER_CREATED = "EXECUTE_COMMAND_SAVE_REQUEST_ORDER_CREATED";
    public static final String EXECUTE_COMMAND_SAVE_PICKUP_TIME = "EXECUTE_COMMAND_SAVE_PICKUP_TIME";
    public static final String EXECUTE_COMMAND_REDEEM_COUPONS = "EXECUTE_COMMAND_REDEEM_COUPONS";
    public static final String EXECUTE_COMMAND_REDEEM_FOOD_COINS = "EXECUTE_COMMAND_REDEEM_FOOD_COINS";
    public static final String EXECUTE_COMMAND_ISSUE_ELECTRONIC_BILLING = "EXECUTE_COMMAND_ISSUE_ELECTRONIC_BILLING";

    //Group
    public static final String EXECUTE_GROUP_COMMAND_CREATE_TRANSACTION = "EXECUTE_GROUP_COMMAND_CREATE_TRANSACTION";

    //Priority
    public static final Integer PRIORITY_ONE = 1;
    public static final Integer PRIORITY_TWO = 2;
    public static final Integer PRIORITY_THREE = 3;
    public static final Integer PRIORITY_FOUR = 4;
    public static final Integer PRIORITY_FIVE = 5;
    public static final Integer PRIORITY_SIX = 6;
    public static final Integer PRIORITY_SEVEN = 7;
    public static final Integer PRIORITY_EIGHT = 8;
    public static final Integer PRIORITY_NINE = 9;
    public static final Integer PRIORITY_TEN = 10;
    public static final Integer PRIORITY_ELEVEN = 11;
}
