apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-ou-config
data:
{{- if or (eq .Values.orderbc.redis.enabled true) ( eq .Values.ordercreation.redis.enabled true) ( eq .Values.taxesbc.redis.enabled true) ( eq .Values.ordercreationqueries.redis.enabled true) ( eq .Values.orderorlocalserver.redis.enabled true)  }}
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        enabled: true
        fields_under_root: true
        multiline:
          match: after
          negate: true
          pattern: '^\['
        paths:
          - /tmp/logs/*.log
        fields:
          squad: '${SQUAD}'
          app: '${APP}'
          environment: '${ENVIRONMENT}'

    output.redis:
      hosts: ['${REDIS_HOST}']
      password: "ukHVef2qWAm0vmuYQ30ILljB"
      key: '${RD_KEY}'
      db: 0
      timeout: 5

    processors:
    - add_docker_metadata:
        host: "unix:///host_docker/docker.sock"
{{- else }}
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        enabled: true
        fields_under_root: true
        multiline:
          match: after
          negate: true
          pattern: '^\['
        paths:
          - /tmp/logs/*.log
        fields:
          squad: '${SQUAD}'
          app: '${APP}'
          environment: '${ENVIRONMENT}'

    output.logstash:
      hosts: ['${LOGSTASH_HOSTS}']
      pipeline: '${PIPELINE}'
      enabled: true

    processors:
    - add_docker_metadata:
        host: "unix:///host_docker/docker.sock"
{{- end }}