{{- if .Values.orderbc.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "servicesou.orderbc.serviceAccountName" . }}
  labels:
    {{- include "servicesou.orderbc.labels" . | nindent 4 }}
  {{- with .Values.orderbc.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
