apiVersion: v1
kind: Service
metadata:
  name: {{ include "changestatus.changestatusbc.fullname" . }}
  labels:
    {{- include "changestatus.changestatusbc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.changestatusbc.service.type }}
  ports:
    - port: {{ .Values.changestatusbc.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "changestatus.changestatusbc.selectorLabels" . | nindent 4 }}
