{{- if and .Values.ordercreationqueries.persistence.enabled (not .Values.ordercreationqueries.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "servicesou.ordercreationqueries.fullname" . }}
spec:
  accessModes:
    - {{ .Values.ordercreationqueries.persistence.accessMode | quote }}
  storageClassName: {{ .Values.ordercreationqueries.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.ordercreationqueries.persistence.size | quote }}
{{- end -}}