apiVersion: v1
kind: ConfigMap
metadata:
  name: changestatus-filebeat-config
data:
{{- if or (eq .Values.changestatusbc.redis.enabled true) ( eq .Values.changestatusor.redis.enabled true) }}
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        enabled: true
        fields_under_root: true
        multiline:
          match: after
          negate: true
          pattern: '^\['
        paths:
          - /tmp/logs/*.log
        fields:
          squad: '${SQUAD}'
          app: '${APP}'
          environment: '${ENVIRONMENT}'

    output.redis:
      hosts: ['${REDIS_HOST}']
      password: "ukHVef2qWAm0vmuYQ30ILljB"
      key: '${RD_KEY}'
      db: 0
      timeout: 5

    processors:
    - add_docker_metadata:
        host: "unix:///host_docker/docker.sock"
{{- else }}
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        enabled: true
        fields_under_root: true
        multiline:
          match: after
          negate: true
          pattern: '^\['
        paths:
          - /tmp/logs/*.log
        fields:
          squad: '${SQUAD}'
          app: '${APP}'
          environment: '${ENVIRONMENT}'

    output.logstash:
      hosts: ['${LOGSTASH_HOSTS}']
      pipeline: '${PIPELINE}'
      enabled: true
      ssl.enabled: true
      ssl.certificate_authorities: ["/etc/certs/ca-cert.crt"]
      ssl.certificate: "/etc/certs/filebeat-cert.crt"
      ssl.key: "/etc/certs/filebeat-key.key"

    processors:
    - add_docker_metadata:
        host: "unix:///host_docker/docker.sock"
{{- end }}