CREATE TABLE `orders` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Almacena las órdenes realizadas',
  `uid` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'UID que identificará el correlativo de la factura',
  `uuid` varchar(50) COLLATE utf8mb4_unicode_ci NULL COMMENT 'UUID Identificador único de la orden',
  `transaction_id` int(10) unsigned NULL COMMENT 'Trasacción asociada a la orden (Relación virtual con tabla -transactions- BD ORDERS)',
  `status_id` int(10) unsigned NOT NULL DEFAULT '1' COMMENT 'Estado de la orden (Relación virtual con tabla -order_status- BD ORDERS)',
  `delivery_type_id` int(10) unsigned NOT NULL DEFAULT '1' COMMENT 'Tipo de entrega: Domicilio o recoger en punto (Relación virtual con tabla -delivery_types- BD ORDERS)',
  `payment_model_id` int(10) unsigned NOT NULL DEFAULT '1' COMMENT 'Indica si el pago es en caja o si es online. Relación virtual con tabla -payment_models- BD ORDERS',
  `workshift_id` int(10) unsigned DEFAULT NULL COMMENT 'Turno del cajero (Relación virtual con workshifts de BD SGI',
  `franchise_id` int(10) unsigned NOT NULL DEFAULT '1' COMMENT 'Identificador de la franquicia (Relación virtual con tabla -franchises- de MUY)',
  `franchise_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nombre de la franquicia',
  `origin_id` int(10) unsigned NOT NULL COMMENT 'Origen de la orden Ej: App, Autogestión (Relación virtual con dic_origins de BD SGI',
  `origin_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nombre del origen de la orden Ej: App, Autogestión',
  `company_id` int(10) unsigned NOT NULL COMMENT 'Id de la compañía (Relación virtual con companies de BD SGI)',
  `store_id` int(10) unsigned NOT NULL COMMENT 'Id de la tienda (Relación virtual con stores de BD SGI)',
  `store_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nombre de la tienda',
  `pos_id` int(10) unsigned NULL COMMENT 'Id de la caja (Relación virtual con pos de SGI)',
  `billing_resolution_id` int(11) DEFAULT NULL COMMENT 'Identificador de la resolución del pos o la caja',
  `user_id` int(10) unsigned NOT NULL COMMENT 'Id del cliente (Relación virtual con tabla users de SGI)',
  `currency` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Identificador de la moneda, mismo del tabla company de SGI',
  `order_number` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Número que se le muestra al cliente, No se debe validar nada con él',
  `order_invoice_number` varchar(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Número de la factura generado mediante la resolución asignada a la caja',
  `paid` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'Indica el estado de la orden. 0:No paga | 1:Pagada | 2:Pendiente',
  `invoice_status_id` smallint(5) unsigned NULL DEFAULT '1' COMMENT 'Indica el id del estado de la factura electronica, 1: No reportada aun, 2: Reportada a la entidad tributaria, 3: No reportada, etc',
  `printed` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'Indica si la orden ya fue impresa. 0:No Impresa | 1:Impresa',
  `number_final_products` int(10) unsigned NOT NULL COMMENT 'Cantidad de productos finales de la orden',
  `subtotal` decimal(13,4) unsigned NOT NULL COMMENT 'Valor de los productos, adiciones, servicios adicionales, etc SIN impuestos',
  `taxes` decimal(13,4) unsigned NOT NULL COMMENT 'Sumatoria de todos los impuestos de la orden',
  `discounts` decimal(13,4) unsigned NOT NULL COMMENT 'Total de los descuentos aplicados',
  `co2_compensation_price` decimal(13,4) NOT NULL DEFAULT 0 COMMENT 'Valor total que el usuario debe pagar por la compensacion CO2',
  `total` decimal(13,4) unsigned NOT NULL COMMENT 'Valor real que paga el cliente',
  `operation_date` date NOT NULL COMMENT 'Fecha real de la compra, no es necesariamente la fecha en la que se inserta en BD',
  `pickup_time` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora de recogida de la orden',
  `local_date` date NOT NULL COMMENT 'Este campo almacena la fecha de la orden Y-m-d',
  `local_time` time NOT NULL COMMENT 'Este campo almacena la hora de la orden H:m:s',
  `enabled_trigger` tinyint(1) DEFAULT 0 NULL COMMENT 'Campo temporal para mantener la sincronización entre todos los sistemas. (Su tiempo de vida es mientras los terceros se integran con orden unifada)',
  `full_synchronized` tinyint DEFAULT 0 COMMENT 'Este campo es una bandera que indica si la orden se sicronizó completamente 0 no | 1 si',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `orders_workshift_id_index` (`workshift_id`),
  KEY `orders_origin_id_index` (`origin_id`),
  KEY `orders_company_id_index` (`company_id`),
  KEY `orders_store_id_index` (`store_id`),
  KEY `orders_pos_id_index` (`pos_id`),
  KEY `orders_user_id_index` (`user_id`),
  KEY `orders_printed_index` (`printed`),
  KEY `orders_invoice_status_id_index` (`invoice_status_id`),
  KEY `orders_franchise_id_index` (`franchise_id`),
  KEY `orders_status_id_index` (`status_id`),
  KEY `orders_delivery_type_id_index` (`delivery_type_id`),
  KEY `orders_payment_model_id_index` (`payment_model_id`),
  KEY `orders_operation_date_index` (`operation_date`),
  KEY `orders_local_date_index` (`local_date`),
  KEY `orders_local_time_index` (`local_time`),
  KEY `orders_uid_index` (`uid`),
  KEY `orders_uuid_index` (`uuid`),
  KEY `orders_transaction_id_index` (`transaction_id`),
  KEY `orders_created_at_store_id_paid_delivery_type_id` (`created_at`,`store_id`,`delivery_type_id`,`paid`),
  UNIQUE (uuid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;