CREATE TABLE `order_integrations` (
  `order_id` int(10) unsigned NOT NULL COMMENT 'Identificador de la orden (Relación viertual tabla -orders- BD ORDERS)',
  `store_id` int(10) unsigned NOT NULL COMMENT 'Id de la tienda (Relación virtual con stores de BD SGI)',
  `store_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nombre de la tienda',
  `franchise_id` int(10) unsigned NOT NULL DEFAULT '1' COMMENT 'Identificador de la franquicia (Relación virtual con tabla -franchises- de MUY)',
  `franchise_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nombre de la franquicia',
  `origin_id` int(10) unsigned NOT NULL COMMENT 'Origen de la orden Ej: App, Autogestión (Relación virtual con dic_origins de BD SGI',
  `origin_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nombre del origen de la orden Ej: App, Autogestión',
  `integration_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Identificador del pedido del lado del tercero',
  `order_type` int(10) unsigned NOT NULL COMMENT 'Identificador del tipo de la orden que nos envía el tercero',
  `code` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Corresponde a un string único (Es como nuestro order number)',
  `user_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nombre del usuario registrado en la plataforma externa',
  `user_phone` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Célular del usuario registrado en la plataforma externa',
  `total_order` decimal(13,4) unsigned NOT NULL COMMENT 'Valor pagado por el cliente en la plataforma externa',
  `total_delivery` decimal(13,4) unsigned NOT NULL COMMENT 'Valor asociado al domicilio',
  `total_discount` decimal(13,4) unsigned NOT NULL COMMENT 'Valor asociado al descuento',
  `total_tip` decimal(13,4) unsigned NOT NULL COMMENT 'Valor asociado a la propina',
  `payment_method` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Método de pago del cliente en la plataforma externa',
  `arrival_date` date NOT NULL COMMENT 'Fecha en la que se programa el pedido para entrega',
  `arrival_time` time NOT NULL COMMENT 'Hora en la que se programa el pedido para entrega',
  `notes` text COLLATE utf8mb4_unicode_ci COMMENT 'Notas asociadas a la orden',
  `address_city` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Ubicación en la ciudad',
  `address_description` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Descripción de ubicación',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`order_id`),
  KEY `order_integrations_store_id_index` (`store_id`),
  KEY `order_integrations_franchise_id_index` (`franchise_id`),
  KEY `order_integrations_origin_id_index` (`origin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
