CREATE TABLE `order_final_product_complements` (
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Almacena los (final products complements)',
    `company_id` int(10) unsigned NOT NULL COMMENT 'Id de la compañía (Relación virtual con companies de BD SGI)',
    `dic_unit_id` int(10) unsigned NOT NULL COMMENT 'Unidad de medida del producto Ej:Bowls (Relación virtual con tabla dic_units de SGI)',
    `operation_date` date NOT NULL COMMENT 'Fecha real del registro, no es necesariamente la fecha en la que se inserta en BD',
    `order_final_product_id` int(10) unsigned NOT NULL COMMENT 'Identificador del producto (Relación virtual tabla -order_final_products- BD ORDERS)',
    `order_id` int(10) unsigned NOT NULL COMMENT 'Identificador de la orden (Relación viertual tabla -orders- BD ORDERS)',
    `product_id` int(10) unsigned NOT NULL COMMENT 'Id del producto Ej:Bowl (Relación virtual con tabla products de SGI)',
    `portion_id` int(10) unsigned NOT NULL DEFAULT '1' COMMENT 'Corresponde al ID de la porción (Relación virtual con tabla -portions- BD SGI)',
    `price` decimal(13,4) unsigned NOT NULL COMMENT 'Precio del los productos',
    `product_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nombre del producto procesado Ej: Bowl',
    `quantity` int(10) unsigned NOT NULL COMMENT 'Cantidad de productos en cuestión',
    `store_id` int(10) unsigned NOT NULL COMMENT 'Id de la tienda (Relación virtual con stores de BD SGI)',
    `units_number` double(8,2) unsigned NOT NULL COMMENT 'Número de unidades del producto Ej: 300g, 500g, 50ml, 3.5g',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `order_final_product_complements_order_id_index` (`order_id`),
    KEY `order_final_product_complements_company_id_index` (`company_id`),
    KEY `order_final_product_complements_store_id_index` (`store_id`),
    KEY `order_final_product_complements_order_final_product_id_index` (`order_final_product_id`),
    KEY `order_final_product_complements_product_id_index` (`product_id`),
    KEY `order_final_product_complements_dic_unit_id_index` (`dic_unit_id`),
    KEY `order_final_product_complements_portion_id_index` (`portion_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
