CREATE TABLE `order_final_products` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Almacena los productos finales asociados a la orden, Ej: MUY Paisa',
  `sku` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'identificador sku del producto',
  `order_id` int(10) unsigned NOT NULL COMMENT 'Id de la orden (Relación virtual con -orders- DB ORDERS)',
  `company_id` int(10) unsigned NOT NULL COMMENT 'Id de la compañía (Relación virtual con companies de BD SGI)',
  `final_product_category_id` int(10) unsigned DEFAULT NULL COMMENT 'Categoría del producto final Ej. Plato, Jugos, gaseosa, etc (Relación virtual con final_product_categories de DB SGI)',
  `final_product_category_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT  'Nombre de la categoría del producto final',
  `final_product_id` int(10) unsigned NOT NULL COMMENT 'Id del producto final (Relación virtual con tabla final_products de DB SGI)',
  `final_product_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nombre del producto final (Ej: MUY Paisa)',
  `size_id` int(10) unsigned NOT NULL COMMENT 'Id del tamaño del producto final (Relación virtual con sizes de DB SGI)',
  `size_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nombre del tamaño del producto final Ej: MUY o MUY MUY',
  `article_id` int(10) unsigned DEFAULT NULL COMMENT 'Identificador del articulo del menú (Relación virtual con el sistema de Menú)',
  `article_type_id` int(10) unsigned DEFAULT NULL COMMENT 'Identificador del tipo articulo del menú, EJ: promoción, producto (Relación virtual con el sistema de Menú)',
  `menu_hall_product_id` int(10) unsigned DEFAULT NULL COMMENT 'Identificador del menú (Relación virtual con el sistema de Menú)',
  `brand_menu_id` int(11) DEFAULT 0 COMMENT 'Identificador de la marca con relación a la base de datos de menú, para la sincronización entre los sistemas de MUY y orders -> TODO: Eliminar cuando salgamos de MUY',
  `brand_id` int(11) DEFAULT 0 COMMENT 'Identificador de la marca, relación virtual con tabla sgi.franchises',
  `brand_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nombre de la marca',
  `image` varchar(2048) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Imagen del producto final',
  `quantity` int(10) unsigned NOT NULL COMMENT 'Cantidad enviada del producto final en cuestión',
  `base_price` decimal(13,4) unsigned NOT NULL COMMENT 'Precio base del producto final',
  `products_price` decimal(13,4) unsigned NOT NULL COMMENT 'Precio de sobrecosto en productos o productos adicionales',
  `discount_price` decimal(13,4) unsigned NOT NULL COMMENT 'Valor del descuento aplicado a los productos finales',
  `co2_compensation_price` decimal(13,4) NOT NULL DEFAULT 0 COMMENT 'Valor por producto que el usuario debe pagar por la compensacion CO2',
  `co2_compensation_price_total` decimal(13,4) NOT NULL DEFAULT 0 COMMENT 'Valor total de la compensacion CO2 multiplicando su cantidad',
  `total` decimal(13,4) unsigned DEFAULT 0 COMMENT 'Valor total pagado por el cliente por el/los productos',
  `total_price_nt` decimal(13,4) unsigned NOT NULL COMMENT 'Precio total de los productos finales sin impuestos (Incluidas adiciones)',
  `total_tax_price` decimal(13,4) unsigned NOT NULL COMMENT 'Valor de los impuestos del producto final (Incluidas adiciones)',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `order_final_products_order_id_index` (`order_id`),
  KEY `order_final_products_company_id_index` (`company_id`),
  KEY `order_final_products_final_product_category_id_index` (`final_product_category_id`),
  KEY `order_final_products_final_product_id_index` (`final_product_id`),
  KEY `order_final_products_size_id_index` (`size_id`),
  KEY `order_final_products_brand_id_index` (`brand_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
