CREATE TABLE `pos_resolutions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `resolution_id` int(10) unsigned DEFAULT NULL COMMENT 'Identificador de la resolucion',
  `pos_id` int(10) unsigned DEFAULT NULL COMMENT 'Identificador de la caja',
  `store_id` int(10) unsigned DEFAULT NULL COMMENT 'Identificador de la tienda',
  `dic_status_id` smallint(5) unsigned DEFAULT NULL COMMENT 'Identificador del estado de la resolución',
  `name` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Nombre de la resolución asociada a la caja',
  `order_number_initial` smallint(5) unsigned DEFAULT NULL COMMENT 'Numero de orden incicial asignado a la caja',
  `prefix` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Prefijo establecido para los consecutivos de la factura',
  `invoice_number_initial` int(11) DEFAULT NULL COMMENT 'Número inicial para el incremento del consecutivo de la factura',
  `invoice_number_end` int(11) DEFAULT NULL COMMENT 'Número final para el incremento del consecutivo de la factura',
  `current` smallint(5) unsigned DEFAULT NULL COMMENT 'Indica si es la resolución por defecto para el pos',
  `initial_date` date DEFAULT NULL COMMENT 'Fecha inicial asignada a la resolución',
  `end_date` date DEFAULT NULL COMMENT 'Fecha final asignada a la resolución',
  `type_document` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Tipo de documento asignado a la resolución',
  `invoice_number_resolutions` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Numero de resoluciones asignadas',
  `invoice_text` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Texto asignado a la resolución que se visualizara en la factura',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `pos_resolutions_resolution_id_index` (`resolution_id`),
  KEY `pos_resolutions_pos_id_index` (`pos_id`),
  KEY `pos_resolutions_store_id_index` (`store_id`),
  KEY `pos_resolutions_dic_status_id_index` (`dic_status_id`),
  KEY `pos_resolutions_current_index` (`current`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
